Repository oxxun21/Code-Catcher-FE, pull requests merged in 2024-04, with the labels that each got.

#97 에러핸들링 함수 추가
  build/assets/index-CBtVUdeS.js
  build/assets/index-o1pTDw6a.js
  build/assets/tooltip_level-CzOeKA-H.svg
  build/assets/tooltip_level-DcN0D8b0.svg
  build/index.html
  src/App.tsx
  src/components/codeCompare/UserAICodeReview.tsx
  src/components/codingTest/SelectLang.tsx
  src/interface/aiFeedback_I.ts
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
  src/utils/handleAxiosError.ts
Labels: ♻️ Refactor

#98 코딩테스트 출력값 추가 및 안내문구 수정 등
  src/api/aiFeedback.ts
  src/components/codeCompare/UserAICodeReview.tsx
  src/components/codingTest/ShowResult.tsx
Labels: ✨ Feature, 🐞 Bug

#102 중간 배포
  src/App.tsx
  src/api/aiFeedback.ts
  src/api/bookmark.ts
  src/components/codeCompare/UserAICodeReview.tsx
  src/components/codingTest/ShowResult.tsx
  src/components/list/Pagination.tsx
  src/interface/bookmark_I.ts
  src/interface/submissionProps_I.ts
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
  src/utils/handleAxiosError.ts
Labels: 🌏 Deploy

#103 기타 디자인 조정
  public/assets/arrow_left.svg
  public/assets/arrow_right.svg
  src/components/card/QuestionCard.tsx
  src/components/list/MypageList.tsx
  src/page/BookmarkList.tsx
  src/page/LastQuestionList.tsx
  src/style/datepicker.tsx
  src/utils/formatDate.ts
Labels: 🐞 Bug, 🖌️ Design

#104 북마크 페이지 반응형
  src/App.tsx
  src/assets/icon_mobile_info.svg
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/components/codingTest/TestDescSection.tsx
  src/components/common/MobilePopup.tsx
  src/hook/index.ts
  src/hook/useWindowSize.tsx
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
Labels: 🖌️ Design

#110 코딩테스트 관련 페이지 반응형
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/components/codeCompare/UserAICodeReview.tsx
  src/components/codingTest/CodeEditor.tsx
  src/components/codingTest/TestResultSection.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: 🐞 Bug, 🖌️ Design

#112 중간 배포
  src/App.tsx
  src/assets/icon_mobile_info.svg
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/components/codeCompare/UserAICodeReview.tsx
  src/components/codingTest/CodeEditor.tsx
  src/components/codingTest/TestDescSection.tsx
  src/components/codingTest/TestResultSection.tsx
  src/components/common/MobilePopup.tsx
  src/hook/index.ts
  src/hook/useWindowSize.tsx
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: 🌏 Deploy

#113 모바일용 480 반응형
  src/App.tsx
  src/assets/arrow_back_header.svg
  src/assets/carousel/carousel_01_mobile.png
  src/assets/carousel/carousel_02_mobile.png
  src/assets/carousel/carousel_03_mobile.png
  src/assets/carousel/carousel_04_mobile.png
  src/assets/carousel/index.ts
  src/assets/flag_en.svg
  src/assets/flag_ko.svg
  src/assets/icon_homePage.svg
  src/assets/icon_myPage.svg
  src/components/calender/MonthlyAchieve.tsx
  src/components/card/UserCard.tsx
  src/components/carousel/SplashCarousel.tsx
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/components/list/MypageList.tsx
  src/page/BookmarkList.tsx
  src/page/Home.tsx
  src/page/LastQuestionList.tsx
  src/page/MyPage.tsx
  src/page/Splash.tsx
  src/style/datepicker.tsx
  src/style/googleTranslate.tsx
Labels: 🖌️ Design

#108 구글 번역 위젯
  src/App.tsx
  src/assets/flag_en.svg
  src/assets/flag_ko.svg
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/style/googleTranslate.tsx
Labels: ✨ Feature

#115 런칭 배포
  src/App.tsx
  src/assets/arrow_back_header.svg
  src/assets/carousel/carousel_01_mobile.png
  src/assets/carousel/carousel_02_mobile.png
  src/assets/carousel/carousel_03_mobile.png
  src/assets/carousel/carousel_04_mobile.png
  src/assets/carousel/index.ts
  src/assets/flag_en.svg
  src/assets/flag_ko.svg
  src/assets/icon_homePage.svg
  src/assets/icon_myPage.svg
  src/components/calender/MonthlyAchieve.tsx
  src/components/card/UserCard.tsx
  src/components/carousel/SplashCarousel.tsx
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/components/list/MypageList.tsx
  src/page/BookmarkList.tsx
  src/page/Home.tsx
  src/page/LastQuestionList.tsx
  src/page/MyPage.tsx
  src/page/Splash.tsx
  src/style/datepicker.tsx
  src/style/googleTranslate.tsx
Labels: 🌏 Deploy

#116 isMobile 변수 임시 제거
  src/page/Home.tsx
Labels: 🐞 Bug

#118 배포 후 홈페이지 헤더 메뉴 보이지 않는 문제 수정
  src/components/common/Header.tsx
  src/page/BookmarkList.tsx
Labels: 🐞 Bug

#121 번역위젯 완전히 헤더에서 완전히 제거
  src/components/common/Header.tsx
Labels: 🐞 Bug

#123 모달 버튼 480 적용
  src/components/card/QuestionCard.tsx
  src/components/common/Header.tsx
  src/page/QuestionSelect.tsx
Labels: 🐞 Bug

#125 구글 번역 위젯 개선
  src/assets/achieve_info.svg
  src/assets/bookmark_empty.svg
  src/assets/last_empty.svg
  src/assets/tooltip_level_en.svg
  src/components/calender/MonthlyAchieve.tsx
  src/components/card/QuestionCard.tsx
  src/components/card/UserCard.tsx
  src/components/carousel/SplashCarousel.tsx
  src/components/common/GalmuriButton.tsx
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/components/index.ts
  src/components/list/MypageList.tsx
  src/components/list/Pagination.tsx
  src/hook/useEventTracker.tsx
  src/page/BookmarkList.tsx
  src/page/Home.tsx
  src/page/LastQuestionList.tsx
  src/page/MyPage.tsx
  src/page/QuestionSelect.tsx
  src/style/googleTranslate.tsx
Labels: 🐞 Bug

#127 에디터 구글번역 위젯 오류 수정 및 GA 개선
  index.html
  public/assets/codee_logo.png
  src/api/login.ts
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/components/codingTest/CodeEditor.tsx
  src/components/codingTest/TestResultSection.tsx
  src/components/common/SquareButton.tsx
  src/components/list/MypageList.tsx
  src/page/BookmarkList.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
  src/page/LastQuestionList.tsx
Labels: ✨ Feature, 🐞 Bug

#128 번역 적용 배포
  index.html
  public/assets/codee_logo.png
  src/api/login.ts
  src/assets/achieve_info.svg
  src/assets/bookmark_empty.svg
  src/assets/last_empty.svg
  src/assets/tooltip_level_en.svg
  src/components/calender/MonthlyAchieve.tsx
  src/components/card/QuestionCard.tsx
  src/components/card/UserCard.tsx
  src/components/carousel/SplashCarousel.tsx
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/components/codingTest/CodeEditor.tsx
  src/components/codingTest/TestResultSection.tsx
  src/components/common/GalmuriButton.tsx
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/components/common/SquareButton.tsx
  src/components/index.ts
  src/components/list/MypageList.tsx
  src/components/list/Pagination.tsx
  src/hook/useEventTracker.tsx
  src/page/Bookmark.tsx
  src/page/BookmarkList.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
  src/page/Home.tsx
  src/page/LastQuestionList.tsx
  src/page/MyPage.tsx
  src/page/QuestionSelect.tsx
  src/style/googleTranslate.tsx
Labels: 🌏 Deploy

#126 북마크 480 디자인 수정
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/components/codingTest/TestDescSection.tsx
  src/page/Bookmark.tsx
Labels: 🖌️ Design

#135 마이페이지 480 반응형 디자인 문제 수정
  src/meta/metaData.ts
  src/page/CodingTest.tsx
  src/page/MyPage.tsx
Labels: 🐞 Bug

#137 구글번역 위젯 쿠키 중복 문제 fix
  src/components/calender/MonthlyAchieve.tsx
  src/components/carousel/SplashCarousel.tsx
  src/components/common/GoogleTranslate.tsx
  src/components/list/MypageList.tsx
  src/page/MyPage.tsx
  src/page/Splash.tsx
Labels: 🐞 Bug

#140 AI 코드 리뷰 로직 확인
  src/api/aiFeedback.ts
Labels: ✅ Test

#139 로그인 만료 시간 지정
  src/api/login.ts
  src/components/common/Header.tsx
  src/hook/index.ts
  src/hook/useAutoLogout.tsx
Labels: 🐞 Bug

#141 구글 번역 위젯 언어 전환 시 removeCookie로 쿠키 중복 방지
  src/components/common/GoogleTranslate.tsx
  src/page/QuestionSelect.tsx
Labels: 🐞 Bug

#142 hotfix 수정 배포
  src/api/aiFeedback.ts
  src/api/login.ts
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/hook/index.ts
  src/hook/useAutoLogout.tsx
  src/page/QuestionSelect.tsx
Labels: 🌏 Deploy

#143 구글 번엿 위젯 토글 문제 헤더 렌더링 최적화하여 fix
  src/components/card/UserCard.tsx
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/components/list/MypageList.tsx
Labels: 🐞 Bug

#147 (#106) fix: 구글번역 위젯 memo 및 쿠키 domian 설정하여 쿠키 중복 문제 fix
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/page/Home.tsx
Labels: 🐞 Bug

#151 마이페이지 리스트 테이블 반응형 정렬 수정
  src/components/list/MypageList.tsx
Labels: 🐞 Bug

#153 구글번역 위젯 js로 goog-te-combo 직접 조작하는 방식으로 변경
  src/components/card/QuestionCard.tsx
  src/components/common/GoogleTranslate.tsx
  src/components/common/Header.tsx
  src/page/Home.tsx
Labels: 🐞 Bug

#157 구글번역 위젯 쿠키 중복 문제 제거
  src/components/common/GoogleTranslate.tsx
Labels: 🐞 Bug
