Repository oxxun21/Code-Catcher-FE, pull requests merged in 2024-03, with the labels that each got.

#15 홈페이지 와이어프레임 UI 구현
  package-lock.json
  src/App.tsx
  src/assets/edit.svg
  src/assets/home_dummy_img.png
  src/components/Carousel/SplashCarousel.tsx
  src/components/common/Header.tsx
  src/components/index.ts
  src/page/Home.tsx
  src/page/Main.tsx
  src/page/Splash.tsx
Labels: 🖌️ Design

#13 Header css 개선 및 로그인 상태에 따라 헤더 버튼 전환
  package-lock.json
  src/components/Carousel/SplashCarousel.tsx
  src/components/common/Header.tsx
  src/components/index.ts
  src/page/Splash.tsx
Labels: 🐞 Bug, 🖌️ Design

#18 Feat/404
  src/App.tsx
  src/assets/goHome.svg
  src/assets/img_404.png
  src/page/NotFound.tsx
  src/style/reset.tsx
Labels: 🖌️ Design

#20 스플래시 화면 및 캐러셀 레이아웃 반응형 개선
  package-lock.json
  package.json
  src/assets/arrow_next.svg
  src/assets/arrow_prev.svg
  src/components/Carousel/SplashCarousel.tsx
  src/page/Splash.tsx
Labels: 🖌️ Design

#22 폰트 확정
  src/assets/custom.d.ts
  src/assets/font.css
  src/style/reset.tsx
Labels: ⚙️ Setting, 🖌️ Design

#24 코드 비교 페이지 추가 수정사항
  src/App.tsx
  src/api/question.ts
  src/assets/icon_bookmark_true.svg
  src/components/codingTest/CodeEditor.tsx
  src/components/codingTest/SelectLang.tsx
  src/components/codingTest/TestDescSection.tsx
  src/components/codingTest/TestResultSection.tsx
  src/interface/question_I.ts
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: ✨ Feature, 🐞 Bug

#29 웹 폰트 적용
  index.html
  src/assets/font.css
  src/style/reset.tsx
Labels: 🐞 Bug, 🖌️ Design

#26 로그인 요청 후 response 데이터 처리
  package-lock.json
  package.json
  src/api/index.ts
  src/api/login.ts
  src/components/card/UserCard.tsx
  src/components/common/Header.tsx
  src/components/index.ts
  src/interface/index.ts
  src/interface/user_I.ts
  src/page/Home.tsx
  src/page/KakaoRedirection.tsx
  src/stores/useUserStore.ts
Labels: ✨ Feature, ♻️ Refactor

#31 코드 비교 페이지 디자인 수정
  src/assets/ChatGPTsCode.svg
  src/assets/ChatGPTsFeedback.svg
  src/assets/MyCode.svg
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: 🐞 Bug, 🖌️ Design

#37 버튼 공통 컴포넌트 생성
  src/components/common/GalmuriButton.tsx
  src/components/common/RoundButton.tsx
  src/components/common/SquareButton.tsx
  src/components/index.ts
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: ✨ Feature, 🖌️ Design

#39 로딩 화면 추가
  src/assets/loading.svg
  src/assets/loading_dot.gif
  src/components/common/Loading.tsx
  src/page/KakaoRedirection.tsx
Labels: 🖌️ Design

#33 문제 선택 화면 UI 구현
  src/App.tsx
  src/assets/star_green.svg
  src/assets/star_transparent.svg.svg
  src/components/card/QuestionCard.tsx
  src/components/index.ts
  src/page/QuestionSelect.tsx
  src/style/reset.tsx
Labels: 🖌️ Design

#42 fix: QuestionCard 스크립트 line-height fix 및 문제 id 표기
  src/components/card/QuestionCard.tsx
Labels: 🐞 Bug

#44 모바일 안내 팝업
  src/App.tsx
  src/assets/icon_mobile_info.svg
  src/components/Carousel/SplashCarousel.tsx
  src/components/common/MobilePopup.tsx
  src/components/index.ts
Labels: ✨ Feature, 🙋🏻‍♀️ Question, 🖌️ Design

#45 코딩테스트 페이지 문제 불러오기
  src/App.tsx
  src/api/question.ts
  src/components/codingTest/TestDescSection.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
  src/utils/BASE_URL.ts
Labels: ✨ Feature

#47 테스트 결과 관련 API 연결
  src/api/scoreSubmit.ts
  src/api/testScoreSubmit.ts
  src/interface/index.ts
  src/interface/scoreSubmit_I.ts
  src/interface/submissionProps_I.ts
  src/interface/testScoreSubmit_I.ts
  src/page/CodingTest.tsx
Labels: ✨ Feature

#48 닉네임 수정 API 요청 및 UserCard 디자인 변경
  src/api/index.ts
  src/api/login.ts
  src/api/nickname.ts
  src/assets/edit.svg
  src/assets/level/cat_lv1.jpg
  src/assets/level/cat_lv2.jpg
  src/assets/level/cat_lv3.jpg
  src/assets/level/cat_lv4.jpg
  src/components/card/UserCard.tsx
  src/interface/user_I.ts
  src/page/Home.tsx
  src/stores/useUserStore.ts
Labels: ✨ Feature, 🖌️ Design

#51 프리텐다드 폰트 변경
  index.html
  src/style/reset.tsx
Labels: 🖌️ Design

#49 실행 결과 섹션 UI 구현
  src/components/codingTest/ShowResult.tsx
  src/components/codingTest/TestResultSection.tsx
  src/page/CodingTest.tsx
Labels: 🖌️ Design

#54 북마크 및 지난 테스트 내역 리스트 css 구현
  src/App.tsx
  src/assets/star_pixel.svg
  src/components/card/UserCard.tsx
  src/components/index.ts
  src/components/list/MypageList.tsx
  src/interface/index.ts
  src/interface/mypageListItem_I.ts
  src/page/Home.tsx
  src/page/MyPage.tsx
Labels: 🖌️ Design

#57 테스트 케이스, 제출 및 채점 기능 구현
  .deployment
  .github/workflows/main_code-catcher-fe.yml
  .vscode/settings.json
  build/assets/carousel_dummy_img-Llf3KFjQ.png
  build/assets/cat_lv1-c2P3dUUu.jpg
  build/assets/cat_lv2-WUPhMkHG.jpg
  build/assets/cat_lv3-BP1lwauz.jpg
  build/assets/cat_lv4-DIrTObis.jpg
  build/assets/icon_test_failed-DwXlXdW3.svg
  build/assets/index-DcEyMeye.js
  build/index.html
  build/routes.json
  package.json
  public/routes.json
  src/api/question.ts
  src/api/scoreSubmit.ts
  src/api/testScoreSubmit.ts
  src/components/card/QuestionCard.tsx
  src/components/codingTest/CodeEditor.tsx
  src/components/codingTest/ShowResult.tsx
  src/components/codingTest/TestResultSection.tsx
  src/interface/index.ts
  src/interface/question_I.ts
  src/interface/scoreSubmit_I.ts
  src/interface/testScoreSubmit_I.ts
  src/page/CodingTest.tsx
  src/utils/BASE_URL.ts
  vite.config.ts
Labels: ✨ Feature, ♻️ Refactor

#59 코드 비교 페이지 기능 연결
  src/App.tsx
  src/api/aiFeedback.ts
  src/api/index.ts
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/interface/aiFeedback_I.ts
  src/interface/index.ts
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: ✨ Feature

#67 마이페이지에 필요한 리스트 api 요청 및 유저 정보 업데이트
  package-lock.json
  package.json
  src/App.tsx
  src/api/bookmarkList.ts
  src/api/index.ts
  src/api/lastQuestionList.ts
  src/api/login.ts
  src/api/monthlyAcheive.ts
  src/api/mypageInfo.ts
  src/api/user.ts
  src/assets/Logo_dark.svg
  src/assets/Logo_light.svg
  src/assets/achieve_info.svg
  src/assets/arrow_left.svg
  src/assets/arrow_right.svg
  src/assets/arrow_right_disabled.svg
  src/assets/arrow_right_lastTests.svg
  src/assets/bookmark_empty.svg
  src/assets/last_empty.svg
  src/assets/profile_dummy_img.png
  src/components/calender/MonthlyAchieve.tsx
  src/components/card/UserCard.tsx
  src/components/common/Header.tsx
  src/components/index.ts
  src/components/list/MypageList.tsx
  src/interface/index.ts
  src/interface/mypageInfo_I.ts
  src/interface/user_I.ts
  src/page/BookmarkList.tsx
  src/page/Home.tsx
  src/page/KakaoRedirection.tsx
  src/page/LastQuestionList.tsx
  src/page/MyPage.tsx
  src/stores/useUserStore.ts
  src/style/datepicker.tsx
  src/utils/formatDate.ts
Labels: ✨ Feature, 🐞 Bug, 🖌️ Design

#65 북마크 페이지
  src/App.tsx
  src/api/bookmark.ts
  src/api/index.ts
  src/components/codeCompare/ReadOnlyEditor.tsx
  src/components/codingTest/ShowResult.tsx
  src/components/codingTest/TestDescSection.tsx
  src/interface/bookmark_I.ts
  src/interface/index.ts
  src/interface/scoreSubmit_I.ts
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
Labels: ✨ Feature, 🖌️ Design

#71 북마크 및 지난 테스트 내역 전체 리스트 페이지
  src/api/bookmarkList.ts
  src/api/index.ts
  src/api/lastQuestionList.ts
  src/api/withdraw.ts
  src/assets/arrow_next.svg
  src/assets/arrow_prev.svg
  src/assets/arrow_slide_next.svg
  src/assets/arrow_slide_prev.svg
  src/assets/carousel/carousel_01.png
  src/assets/carousel/carousel_02.png
  src/assets/carousel/carousel_03.png
  src/assets/carousel/carousel_04.png
  src/assets/carousel/index.ts
  src/assets/carousel_dummy_img.png
  src/assets/checked.svg
  src/assets/icon_tooltip.svg
  src/assets/level/cat_lv5.jpg
  src/assets/level/index.ts
  src/components/card/QuestionCard.tsx
  src/components/card/UserCard.tsx
  src/components/carousel/SplashCarousel.tsx
  src/components/common/Header.tsx
  src/components/list/Pagination.tsx
  src/interface/index.ts
  src/interface/mypageInfo_I.ts
  src/interface/mypageListAll_I.ts
  src/interface/mypageListItem_I.ts
  src/page/BookmarkList.tsx
  src/page/Home.tsx
  src/page/LastQuestionList.tsx
  src/page/QuestionSelect.tsx
  src/page/Splash.tsx
Labels: ✨ Feature, 🖌️ Design

#73 기능 씽크 관련 수정 사항 반영
  src/api/bookmark.ts
  src/assets/icon_bookmark_true.svg
  src/interface/bookmark_I.ts
  src/interface/submissionProps_I.ts
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: ✨ Feature, 🖌️ Design

#76 코딩 테스트 관련 기능 씽크
  src/components/codingTest/CodeEditor.tsx
  src/components/common/Gutter.tsx
  src/components/common/SquareButton.tsx
  src/components/index.ts
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: ✨ Feature, 🐞 Bug, ♻️ Refactor

#77 fix
  src/components/codingTest/TestResultSection.tsx
  src/components/common/Header.tsx
  src/components/common/MobilePopup.tsx
  src/components/common/Modal.tsx
  src/hook/useDraggable.tsx
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: 🐞 Bug

#78 add favicon
  index.html
  public/favicon.ico
Labels: 🖌️ Design

#81 디자인 씽크 2차 및 메타 태그 페이지별 적용
  src/App.tsx
  src/assets/meta/bookmark.png
  src/assets/meta/codingTest.png
  src/assets/meta/home.png
  src/assets/meta/index.ts
  src/assets/meta/lastQuestion.png
  src/assets/meta/myPage.png
  src/assets/meta/questionSelect.png
  src/assets/meta/splash.png
  src/components/calender/MonthlyAchieve.tsx
  src/components/card/UserCard.tsx
  src/components/index.ts
  src/meta/metaData.ts
  src/page/BookmarkList.tsx
  src/page/CodingTest.tsx
  src/page/Home.tsx
  src/page/LastQuestionList.tsx
  src/page/MyPage.tsx
  src/page/QuestionSelect.tsx
  src/page/Splash.tsx
  src/style/datepicker.tsx
Labels: 🐞 Bug, 🖌️ Design

#85 배포 후 디자인 오류 수정
  src/components/codingTest/SelectLang.tsx
  src/components/common/Gutter.tsx
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
Labels: 🐞 Bug

#88 AI 유저 피드백 실제 API 연결 및 디자인 반영
  src/api/aiFeedback.ts
  src/components/codeCompare/UserAICodeReview.tsx
  src/components/codingTest/SelectLang.tsx
  src/components/codingTest/TestDescSection.tsx
  src/components/common/Gutter.tsx
  src/interface/aiFeedback_I.ts
  src/page/Bookmark.tsx
  src/page/CodeCompare.tsx
  src/page/CodingTest.tsx
Labels: ✨ Feature, 🖌️ Design
